[hololens]
package = "holo/lens-mkdocs"
requirements = [
    "fontawesome_markdown",
    "mdx_truly_sane_lists",
    "mkdocs-awesome-pages-plugin",
    "mkdocs-exclude",
    "mkdocs-macros-plugin",
    "mkdocs-material",
]

# [hololens.mkdocs]
# config = "docs/mkdocs.yml"
# [hololens.input]
# root = "docs"

[hololens.output]
merge = "replace"
