[hololens]
container = "ghcr.io/hologit/lenses/mkdocs:latest"
requirements = [
    "fontawesome_markdown",
    "mkdocs-awesome-pages-plugin",
    "mkdocs-macros-plugin",
    "mkdocs-material",
]

[hololens.output]
merge = "replace"
