site_name: Skeleton Docs
site_url: https://jarvusinnovations.github.io/emergence-skeleton
edit_uri: edit/develop/docs

# docs_dir: .
# site_dir: ../docs-site

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "orange"
    accent: "red"

plugins:
  - search
  - awesome-pages
  - macros
  - exclude:
      glob:
        - mkdocs.yml
        - mkdocs.*.yml

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '!!python/name:pymdownx.superfences.fence_div_format'
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
  - mdx_truly_sane_lists

extra:
  repository:
    name: emergence-skeleton
    url: git@github.com:JarvusInnovations/emergence-skeleton.git
  studio:
    web_port: 7080
    static_port: ~
    docs_port: 7088
    mysql_port: 7036
  fixtures:
    users:
      - username: system
        password: system
        level: Developer
        about: 'Full system access'
      - username: admin
        password: admin
        level: Administrator
        about: 'Manage site and staff'
      - username: staff
        password: staff
        level: Staff
        about: 'Staff access'
      - username: user
        password: user
        level: User
        about: 'Regular user'
