[holomapping]
files = [
    "*/**",
    # "mkdocs.yml",
    # "mkdocs.*.yml",

    # exclude CI and developer assets
    "!.github/",
    "!.holo/lenses/mkdocs.toml",
    "!.vscode/",
    "!php-config/Git.config.d/",
    "!script/",
]
after = "*"
