#!/bin/bash

# script/test-interactive: Run all tests interactively with Cypress GUI

set -e
cd "$(dirname "$0")/.."


repo_path="$(pwd)"
temp_path="${repo_path}.cypress-workspace"


echo
echo "==> test: setting up temporary workspace diretory…"
if [ -d "${temp_path}" ]; then
    echo "removing existing content..."
    if [ -d "${temp_path}/merged" ] && mount | grep -q "${temp_path}/merged"; then
        sudo umount -f "${temp_path}/merged"
    fi
    rm -rf "${temp_path}"
fi

mkdir -pv "${temp_path}/base"
mkdir -pv "${temp_path}/merged"


echo
echo "==> test: projecting Cypress workspace…"
workspace_tree="$(git holo project cypress-workspace)"

if [ -z "${workspace_tree}" ]; then
    echo
    echo "==> test: failed to project Cypress workspace"
    exit 1
fi


echo
echo "==> test: writing Cypress workspace…"
git archive "${workspace_tree}" --format=tar | (cd "${temp_path}/base" && tar -xf -)


echo
echo "==> test: setting up overlay mount…"

unionfs -o cow \
    -o allow_other,use_ino,suid,dev \
    "${repo_path}"=RW:"${temp_path}/base"=RO \
    "${temp_path}/merged"


echo
echo "==> test: installing node_modules…"
(cd "${temp_path}/merged" && npm install)


echo
echo "==> test: executing \`cypress open\`…"
(cd "${temp_path}/merged" && npx cypress open)
